@api_HostAddress = https://localhost:64675

GET {{api_HostAddress}}/randomdadjoke/
Accept: application/json

###

GET {{api_HostAddress}}/dadjoke/R7UfaahVfFd
Accept: application/json
###


GET {{api_HostAddress}}/solrping

###


POST {{api_HostAddress}}/solrsearch

###


GET {{api_HostAddress}}/test

###

GET {{api_HostAddress}}/solrcorestatus

###

POST {{api_HostAddress}}/initSolr

###
