---
ID: "e1ac3198-3777-4384-bc78-4950e092dffe"
Parent: "ccf5d170-13bf-43fe-9a3c-ed278bc9ff2b"
Template: "ccf5d170-13bf-43fe-9a3c-ed278bc9ff2b"
Path: "/sitecore/templates/Project/team-asmblii/Headless Site/__Standard Values"
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20250308T153257Z
    - ID: "52807595-0f8f-4b20-8d2a-cb71d28c6103"
      Hint: __Owner
      Value: |
        sitecore\pdb@asmblii.com
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\pdb@asmblii.com
    - ID: "8cdc337e-a112-42fb-bbb4-4143751e123f"
      Hint: __Revision
      Value: "e444793a-90b5-4d6c-aea4-e48f78c92505"
    - ID: "badd9cf9-53e0-4d0c-bcc0-2d784c282f6a"
      Hint: __Updated by
      Value: |
        sitecore\pdb@asmblii.com
    - ID: "d9cf14b1-fa16-4ba6-9288-e8a174d4d522"
      Hint: __Updated
      Value: 20250308T153257Z
