services:
  api-solr:
    build:
      context: ./docker/build/solr
      args:
        PARENT_IMAGE: scr.sitecore.com/sxp/nonproduction/solr:8.11.2-ltsc2022
    isolation: ${ISOLATION}
    volumes:
      - .\docker\data\solr:C:\data
    environment:
      SOLR_MODE: solrcloud
      SOLR_LOG_LEVEL: WARN
      SOLR_HEAP: 2000M
      SOLR_JAVA_MEM: -Xms2000M -Xmx2000M
      SOLR_OPTS: -Dlog4j2.formatMsgNoLookups=true -javaagent:C:/solr/server/solr-webapp/webapp/WEB-INF/lib/opentelemetry-javaagent.jar
      OTEL_SERVICE_NAME: api-solr
      OTEL_JAVAAGENT_LOGGING: simple
      OTEL_JAVAAGENT_DEBUG: "false"
      OTEL_EXPORTER_OTLP_ENDPOINT: http://aspire:18889
      OTEL_EXPORTER_OTLP_PROTOCOL: grpc
      OTEL_TRACES_SAMPLER: always_on
    healthcheck:
      test:
        [
          "CMD",
          "powershell",
          "-command",
          "try { $$statusCode = (iwr http://localhost:8983/solr/admin/cores?action=STATUS -UseBasicParsing).StatusCode; if ($$statusCode -eq 200) { exit 0 } else { exit 1} } catch { exit 1 }",
        ]
    labels:
      - "traefik.enable=true"
      - "traefik.http.services.api-solr.loadbalancer.server.port=8983"
      - "traefik.http.routers.api-solr.entrypoints=websecure"
      - "traefik.http.routers.api-solr.rule=Host(`api-solr.2025-team-asmblii.localhost`)"
      - "traefik.http.routers.api-solr.tls=true"
    deploy:
      resources:
        limits:
          cpus: "2"
          memory: 3GB

  api-app:
    build:
      context: .
    isolation: ${ISOLATION}
    environment:
      SOLR__URI: http://api-solr:8983/solr
      OTLPEXPORTER__ENDPOINT: http://aspire:18889
    labels:
      - "traefik.enable=true"
      - "traefik.http.services.api-app.loadbalancer.server.port=8080"
      - "traefik.http.routers.api-app.entrypoints=websecure"
      - "traefik.http.routers.api-app.rule=Host(`api-app.2025-team-asmblii.localhost`)"
      - "traefik.http.routers.api-app.tls=true"